-- MySQL Script generated by MySQL Workbench
-- Tue Feb 13 17:54:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CapstoneFish
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CapstoneFish
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CapstoneFish` DEFAULT CHARACTER SET utf8 ;
USE `CapstoneFish` ;

-- -----------------------------------------------------
-- Table `CapstoneFish`.`Tanks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CapstoneFish`.`Tanks` ;

CREATE TABLE IF NOT EXISTS `CapstoneFish`.`Tanks` (
  `Tanks_Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Length` INT NULL,
  `Width` INT NULL,
  `Height` INT NULL,
  `Measurement` VARCHAR(45) NOT NULL,
  `Cost` FLOAT NULL,
  PRIMARY KEY (`Tanks_Id`),
  UNIQUE INDEX `Tanks_Id_UNIQUE` (`Tanks_Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapstoneFish`.`Fishs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CapstoneFish`.`Fishs` ;

CREATE TABLE IF NOT EXISTS `CapstoneFish`.`Fishs` (
  `Fishs_Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Cost` FLOAT NULL,
  PRIMARY KEY (`Fishs_Id`),
  UNIQUE INDEX `Fishs_Id_UNIQUE` (`Fishs_Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapstoneFish`.`Plants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CapstoneFish`.`Plants` ;

CREATE TABLE IF NOT EXISTS `CapstoneFish`.`Plants` (
  `Plants_Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Cost` FLOAT NULL,
  PRIMARY KEY (`Plants_Id`),
  UNIQUE INDEX `Plants_Id_UNIQUE` (`Plants_Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapstoneFish`.`Decorations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CapstoneFish`.`Decorations` ;

CREATE TABLE IF NOT EXISTS `CapstoneFish`.`Decorations` (
  `Decorations_Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Cost` FLOAT NULL,
  PRIMARY KEY (`Decorations_Id`),
  UNIQUE INDEX `Decorations_Id_UNIQUE` (`Decorations_Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapstoneFish`.`Heaters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CapstoneFish`.`Heaters` ;

CREATE TABLE IF NOT EXISTS `CapstoneFish`.`Heaters` (
  `Heaters_Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Cost` FLOAT NULL,
  PRIMARY KEY (`Heaters_Id`),
  UNIQUE INDEX `Heaters_Id_UNIQUE` (`Heaters_Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapstoneFish`.`Cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CapstoneFish`.`Cart` ;

CREATE TABLE IF NOT EXISTS `CapstoneFish`.`Cart` (
  `Cart_Id` INT NOT NULL,
  `Tanks_Id` INT NULL,
  `Fishs_Id` INT NULL,
  `Cost` FLOAT NULL,
  `Plants_Id` INT NULL,
  `Decorations_Id` INT NULL,
  `Heaters_Id` INT NULL,
  PRIMARY KEY (`Cart_Id`),
  UNIQUE INDEX `Tanks_Id` (`Tanks_Id` ASC) VISIBLE,
  UNIQUE INDEX `Fishs_Id` (`Fishs_Id` ASC) INVISIBLE,
  UNIQUE INDEX `Plants_Id` (`Plants_Id` ASC) VISIBLE,
  UNIQUE INDEX `Decorations_Id` (`Decorations_Id` ASC) VISIBLE,
  UNIQUE INDEX `Heaters_Id` (`Heaters_Id` ASC) VISIBLE,
  UNIQUE INDEX `Cost_UNIQUE` (`Cost` ASC) VISIBLE,
  CONSTRAINT `Tanks_Id`
    FOREIGN KEY (`Tanks_Id`)
    REFERENCES `CapstoneFish`.`Tanks` (`Tanks_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fishs_Id`
    FOREIGN KEY (`Fishs_Id`)
    REFERENCES `CapstoneFish`.`Fishs` (`Fishs_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Plants_Id`
    FOREIGN KEY (`Plants_Id`)
    REFERENCES `CapstoneFish`.`Plants` (`Plants_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Decorations_Id`
    FOREIGN KEY (`Decorations_Id`)
    REFERENCES `CapstoneFish`.`Decorations` (`Decorations_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Heaters_Id`
    FOREIGN KEY (`Heaters_Id`)
    REFERENCES `CapstoneFish`.`Heaters` (`Heaters_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapstoneFish`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CapstoneFish`.`Order` ;

CREATE TABLE IF NOT EXISTS `CapstoneFish`.`Order` (
  `Order_Id` INT NOT NULL,
  `Cart_Id` INT NULL,
  `Status` TINYINT NULL,
  PRIMARY KEY (`Order_Id`),
  INDEX `Cart_Id_idx` (`Cart_Id` ASC) VISIBLE,
  CONSTRAINT `Cart_Id`
    FOREIGN KEY (`Cart_Id`)
    REFERENCES `CapstoneFish`.`Cart` (`Cart_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapstoneFish`.`Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CapstoneFish`.`Member` ;

CREATE TABLE IF NOT EXISTS `CapstoneFish`.`Member` (
  `Member_Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`Member_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapstoneFish`.`Guest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CapstoneFish`.`Guest` ;

CREATE TABLE IF NOT EXISTS `CapstoneFish`.`Guest` (
  `Guest` TINYINT NOT NULL,
  PRIMARY KEY (`Guest`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CapstoneFish`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CapstoneFish`.`User` ;

CREATE TABLE IF NOT EXISTS `CapstoneFish`.`User` (
  `Member_Id` INT NULL,
  `Guest` TINYINT NOT NULL,
  `Order_Id` INT NULL,
  `Cart_Id` INT NULL,
  INDEX `Cart_Id` (`Cart_Id` ASC) VISIBLE,
  INDEX `Order_Id` (`Order_Id` ASC) VISIBLE,
  INDEX `Member_Id` (`Member_Id` ASC) INVISIBLE,
  INDEX `Guest` (`Guest` ASC) VISIBLE,
  CONSTRAINT `Cart_Id`
    FOREIGN KEY (`Cart_Id`)
    REFERENCES `CapstoneFish`.`Cart` (`Cart_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Order_Id`
    FOREIGN KEY (`Order_Id`)
    REFERENCES `CapstoneFish`.`Order` (`Order_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Member_Id`
    FOREIGN KEY (`Member_Id`)
    REFERENCES `CapstoneFish`.`Member` (`Member_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Guest`
    FOREIGN KEY (`Guest`)
    REFERENCES `CapstoneFish`.`Guest` (`Guest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `CapstoneFish`.`Tanks`
-- -----------------------------------------------------
START TRANSACTION;
USE `CapstoneFish`;
INSERT INTO `CapstoneFish`.`Tanks` (`Tanks_Id`, `Name`, `Length`, `Width`, `Height`, `Measurement`, `Cost`) VALUES (1, 'Jones Special Tanks', 4, 5, 12, 'Inches', 40.99);
INSERT INTO `CapstoneFish`.`Tanks` (`Tanks_Id`, `Name`, `Length`, `Width`, `Height`, `Measurement`, `Cost`) VALUES (2, 'Jaxs Tanks', 5, 6, 10, 'Inches', 62.99);
INSERT INTO `CapstoneFish`.`Tanks` (`Tanks_Id`, `Name`, `Length`, `Width`, `Height`, `Measurement`, `Cost`) VALUES (3, 'Westward Tanks', 6, 6, 8, 'Inches', 51.99);
INSERT INTO `CapstoneFish`.`Tanks` (`Tanks_Id`, `Name`, `Length`, `Width`, `Height`, `Measurement`, `Cost`) VALUES (4, 'Jonny\'s Medium Tanks', 5, 10, 12, 'Inches', 40.99);
INSERT INTO `CapstoneFish`.`Tanks` (`Tanks_Id`, `Name`, `Length`, `Width`, `Height`, `Measurement`, `Cost`) VALUES (5, 'Steel Max Maga Tanks', 25, 10, 20, 'Inches', 60.99);

COMMIT;


-- -----------------------------------------------------
-- Data for table `CapstoneFish`.`Fishs`
-- -----------------------------------------------------
START TRANSACTION;
USE `CapstoneFish`;
INSERT INTO `CapstoneFish`.`Fishs` (`Fishs_Id`, `Name`, `Cost`) VALUES (1, 'Mickey Mouse Platy', 12.99);
INSERT INTO `CapstoneFish`.`Fishs` (`Fishs_Id`, `Name`, `Cost`) VALUES (2, 'Guppies', 12.99);
INSERT INTO `CapstoneFish`.`Fishs` (`Fishs_Id`, `Name`, `Cost`) VALUES (3, 'Zebra Danio', 13.99);
INSERT INTO `CapstoneFish`.`Fishs` (`Fishs_Id`, `Name`, `Cost`) VALUES (4, 'Neon Tetra', 13.99);
INSERT INTO `CapstoneFish`.`Fishs` (`Fishs_Id`, `Name`, `Cost`) VALUES (5, 'White Cloud Mountain Minnow', 10.99);
INSERT INTO `CapstoneFish`.`Fishs` (`Fishs_Id`, `Name`, `Cost`) VALUES (6, 'Tiger Barb', 9.99);

COMMIT;


-- -----------------------------------------------------
-- Data for table `CapstoneFish`.`Plants`
-- -----------------------------------------------------
START TRANSACTION;
USE `CapstoneFish`;
INSERT INTO `CapstoneFish`.`Plants` (`Plants_Id`, `Name`, `Cost`) VALUES (1, 'Dwarf Anubias', 2.99);
INSERT INTO `CapstoneFish`.`Plants` (`Plants_Id`, `Name`, `Cost`) VALUES (2, 'Java Fern', 3.99);
INSERT INTO `CapstoneFish`.`Plants` (`Plants_Id`, `Name`, `Cost`) VALUES (3, 'Moneywort', 2.99);
INSERT INTO `CapstoneFish`.`Plants` (`Plants_Id`, `Name`, `Cost`) VALUES (4, 'Parrot\'s Feather', 3.99);
INSERT INTO `CapstoneFish`.`Plants` (`Plants_Id`, `Name`, `Cost`) VALUES (5, 'Marimo Moss Balls', 4.99);

COMMIT;


-- -----------------------------------------------------
-- Data for table `CapstoneFish`.`Decorations`
-- -----------------------------------------------------
START TRANSACTION;
USE `CapstoneFish`;
INSERT INTO `CapstoneFish`.`Decorations` (`Decorations_Id`, `Name`, `Cost`) VALUES (1, 'Rocks', 2.99);
INSERT INTO `CapstoneFish`.`Decorations` (`Decorations_Id`, `Name`, `Cost`) VALUES (2, 'Underwater Tree', 4.99);
INSERT INTO `CapstoneFish`.`Decorations` (`Decorations_Id`, `Name`, `Cost`) VALUES (3, 'SpongeBob house', 12.99);
INSERT INTO `CapstoneFish`.`Decorations` (`Decorations_Id`, `Name`, `Cost`) VALUES (4, 'Large Rocks', 4.99);
INSERT INTO `CapstoneFish`.`Decorations` (`Decorations_Id`, `Name`, `Cost`) VALUES (5, 'Hollow Rocks And Tree Set', 19.99);

COMMIT;


-- -----------------------------------------------------
-- Data for table `CapstoneFish`.`Heaters`
-- -----------------------------------------------------
START TRANSACTION;
USE `CapstoneFish`;
INSERT INTO `CapstoneFish`.`Heaters` (`Heaters_Id`, `Name`, `Cost`) VALUES (1, 'Jonny Hang-On-Back Heater', 12.99);
INSERT INTO `CapstoneFish`.`Heaters` (`Heaters_Id`, `Name`, `Cost`) VALUES (2, 'Jones Submersible Heater', 14.99);
INSERT INTO `CapstoneFish`.`Heaters` (`Heaters_Id`, `Name`, `Cost`) VALUES (3, 'Stone\'s Inline Heater', 9.99);
INSERT INTO `CapstoneFish`.`Heaters` (`Heaters_Id`, `Name`, `Cost`) VALUES (4, 'Luther Canister Heater', 15.99);
INSERT INTO `CapstoneFish`.`Heaters` (`Heaters_Id`, `Name`, `Cost`) VALUES (5, 'Carry\'s Infrared Heater', 12.99);

COMMIT;


-- -----------------------------------------------------
-- Data for table `CapstoneFish`.`Member`
-- -----------------------------------------------------
START TRANSACTION;
USE `CapstoneFish`;
INSERT INTO `CapstoneFish`.`Member` (`Member_Id`, `Name`, `Password`) VALUES (1, 'Steve', '123');
INSERT INTO `CapstoneFish`.`Member` (`Member_Id`, `Name`, `Password`) VALUES (2, 'John', '123');
INSERT INTO `CapstoneFish`.`Member` (`Member_Id`, `Name`, `Password`) VALUES (3, 'Carry', '123');
INSERT INTO `CapstoneFish`.`Member` (`Member_Id`, `Name`, `Password`) VALUES (4, 'Lena', '123');
INSERT INTO `CapstoneFish`.`Member` (`Member_Id`, `Name`, `Password`) VALUES (5, 'Cherry', '123');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CapstoneFish`.`Guest`
-- -----------------------------------------------------
START TRANSACTION;
USE `CapstoneFish`;
INSERT INTO `CapstoneFish`.`Guest` (`Guest`) VALUES (1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `CapstoneFish`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `CapstoneFish`;
INSERT INTO `CapstoneFish`.`User` (`Member_Id`, `Guest`, `Order_Id`, `Cart_Id`) VALUES (NULL, 1, NULL, NULL);
INSERT INTO `CapstoneFish`.`User` (`Member_Id`, `Guest`, `Order_Id`, `Cart_Id`) VALUES (1, 0, 1, 1);
INSERT INTO `CapstoneFish`.`User` (`Member_Id`, `Guest`, `Order_Id`, `Cart_Id`) VALUES (2, 0, 2, 2);
INSERT INTO `CapstoneFish`.`User` (`Member_Id`, `Guest`, `Order_Id`, `Cart_Id`) VALUES (3, 0, 3, 3);
INSERT INTO `CapstoneFish`.`User` (`Member_Id`, `Guest`, `Order_Id`, `Cart_Id`) VALUES (4, 0, 4, 4);
INSERT INTO `CapstoneFish`.`User` (`Member_Id`, `Guest`, `Order_Id`, `Cart_Id`) VALUES (5, 0, 5, 5);

COMMIT;

